name: CI App with githubactions with web
on:
    push:
        branches: 
            - main
        paths: 
            - apps/web/**
            
defaults:
  run:
    working-directory: ./apps/web

jobs:
    
    log:
        runs-on: ubuntu-latest
    
        steps:
             
            - name: checkout repo
              uses: actions/checkout@v5
            
            - name: logging app_name
              run : echo ${{ github.repository_owner }}
    
    start:

        strategy:
            matrix:
                os: ["windows-latest","macos-latest","ubuntu-latest"]

        runs-on: ${{matrix.os}}
        
        steps:
            - name: checkout repo
              uses: actions/checkout@v5
            
            - name: setup node
              uses: actions/setup-node@v6
              with:
                node-version : 22
            
            - uses: pnpm/action-setup@v6
              name: Install pnpm
              with:
                version: 10

            - name: installing dependencies
              run: pnpm i

            - name: running script
              run: pnpm run start

